services:
  mysql:
    image: mariadb:11.4
    logging:
      driver: none
    command: ["--max-allowed-packet=512M"]
    volumes:
      - "../files/data/db:/var/lib/mysql:delegated"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    networks:
      - dokploy-network
  litespeed:
    image: litespeedtech/openlitespeed:${OLS_VERSION}-${PHP_VERSION}
    container_name: litespeed
    env_file:
      - .env
    volumes:
      - ../files/lsws/conf:/usr/local/lsws/conf
      - ../files/lsws/admin-conf:/usr/local/lsws/admin/conf
      - ../files/bin/container:/usr/local/bin
      - ../files/sites:/var/www/vhosts/
      - ../files/acme:/root/.acme.sh/
      - ../files/logs:/usr/local/lsws/logs/
    expose:
      - 80
      - 443
      - 443/udp
      - 7080
    restart: always
    environment:
      TZ: ${TimeZone}
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.constraint-label-stack=wordpress
  # phpmyadmin:
  #   image: bitnami/phpmyadmin:5.2.0-debian-11-r43
  #   ports:
  #     - 8080:8080
  #     - 8443:8443
  #   environment:
  #       DATABASE_HOST: mysql
  #   restart: always
  #   networks:
  #     - default
  redis:
    image: "redis:alpine"
    logging:
      driver: none
    # command: redis-server --requirepass 8b405f60665e48f795752e534d93b722
    volumes:
      - ../files/redis/data:/var/lib/redis
      - ../files/redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    restart: always
    networks:
      - dokploy-network
networks:
  dokploy-network:
    external: true
